services:
  dam-lab-2-db:
    container_name: dam-lab-2-db
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: dam
      POSTGRES_USER: dam
      POSTGRES_PASSWORD: password
